version: '3.11'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./templates:/app/templates

    environment:
      - PYTHONUNBUFFERED=1
